### ISSUE TITLE
Document querying our event store and setting up one

### ISSUE THREAD

**Issue by andreipope** [loomnetwork/loom-sdk-documentation#210]
Document querying our event store and setting up one

**Comment by pathornteng** [comment]
Event Store allows users to query events emitted from contracts running on our chain.

The following is the config to enable `Event Store`
```
EventStore:
  DBName: {{.EventStore.DBName}} // Set DB name (can be anything, default is events)
  DBBackend: {{.EventStore.DBBackend}} // Set DB type 'goleveldb' or 'cleveldb'
{{end}}

EventDispatcher:
  Dispatcher: {{.EventDispatcher.Dispatcher}} // Available dispatcher: "db_indexer" | "log" | "redis"
  # Redis will be use when Dispatcher is "redis"
  Redis:
    URI: "{{.EventDispatcher.Redis.URI}}"// Redis URI
```

Config example
```
EventDispatcher:
  Dispatcher: db_indexer

EventStore:
  DBName: "event"
  DBBackend: "goleveldb"
```

Now you can query emitted event `fromBlock` to `toBlock` 

https://plasma.dappchains.com/query/contractevents?fromBlock=5216332&toBlock=5216352
